apiVersion: v1
kind: Service
metadata:
  name: analytic-service
spec:
  type: ClusterIP
  selector:
    app: analytic
  ports:
    - name: analytic-port
      protocol: TCP
      port: 8080
      targetPort: 8080